-- +goose Down
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS service_invoices CASCADE;
DROP TABLE IF EXISTS disbursements CASCADE;
DROP TABLE IF EXISTS opex_requests CASCADE;
DROP TABLE IF EXISTS supplier_invoice_allocations CASCADE;
DROP TABLE IF EXISTS supplier_invoices CASCADE;
DROP TABLE IF EXISTS purchase_order_items CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS purchase_request_items CASCADE;
DROP TABLE IF EXISTS purchase_requests CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS job_order_events CASCADE;
DROP TABLE IF EXISTS job_order_items CASCADE;
DROP TABLE IF EXISTS job_orders CASCADE;
DROP TABLE IF EXISTS sales_quotation_items CASCADE;
DROP TABLE IF EXISTS sales_quotations CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

DROP TYPE IF EXISTS quote_status CASCADE;
DROP TYPE IF EXISTS item_type CASCADE;
DROP TYPE IF EXISTS jo_status CASCADE;
DROP TYPE IF EXISTS pr_status CASCADE;
DROP TYPE IF EXISTS po_status CASCADE;
DROP TYPE IF EXISTS si_status CASCADE;
DROP TYPE IF EXISTS opex_status CASCADE;
DROP TYPE IF EXISTS disbursement_status CASCADE;
DROP TYPE IF EXISTS service_invoice_status CASCADE;

DROP DOMAIN IF EXISTS cents CASCADE;
