import { notFound } from 'next/navigation';
import { headers } from 'next/headers';
import { db } from '@/lib/db';
import { revalidatePath } from 'next/cache';
import {
  assignTechnician,
  transitionJobOrderStatus,
  addJobOrderEvent,
} from '@/lib/actions/job-orders';
import { auth } from '@/lib/auth';
import { hasPermission } from '@/lib/roles';
import { Camera, CalendarDays, Plus } from 'lucide-react';
import StatusWorkflowStepper from '@/components/status-workflow-stepper';

const STATUS_OPTIONS = [
  'DRAFT',
  'APPROVED',
  'IN_PROGRESS',
  'PARTS_PENDING',
  'COMPLETED',
  'BILLED',
  'CLOSED',
];

export default async function JobOrderDetailPage({ params }: { params: { id: string } }) {
  const jo = await db.jobOrder.findUnique({
    where: { joNo: params.id },
    include: {
      customer: true,
      vehicle: true,
      items: true,
      events: { orderBy: { createdAt: 'desc' } },
      serviceInvoice: true,
      invoiceAllocations: true,
    },
  });
  if (!jo) notFound();

  const session = await auth.api.getSession({ headers: headers() });
  const canManage = hasPermission(session?.user.role, 'joChangeStatus');
  const canUpload = hasPermission(session?.user.role, 'attachmentUpload');
  const jobOrder = jo!;

  async function assignFormAction(formData: FormData) {
    'use server';
    const technician = formData.get('technician') as string;
    await assignTechnician(jobOrder.id, technician);
  }

  async function statusFormAction(formData: FormData) {
    'use server';
    const nextStatus = formData.get('nextStatus') as string;
    await transitionJobOrderStatus(
      jobOrder.id,
      nextStatus as Parameters<typeof transitionJobOrderStatus>[1]
    );
  }

  async function eventFormAction(formData: FormData) {
    'use server';
    await addJobOrderEvent(
      jobOrder.id,
      String(formData.get('eventType')),
      String(formData.get('description'))
    );
  }

  async function photoFormAction(formData: FormData) {
    'use server';
    // Photo upload is recorded as an Attachment placeholder. Actual B2 upload is performed client-side
    // via presigned URL generated by a dedicated server action to avoid multipart in server actions.
    const fileName = String(formData.get('fileName'));
    const storageKey = String(formData.get('storageKey'));
    const contentType = String(formData.get('contentType'));
    const size = Number(formData.get('size')) || 0;

    await db.attachment.create({
      data: {
        entityType: 'JOB_ORDER',
        entityId: jobOrder.id,
        fileName,
        contentType,
        size,
        storageKey,
        uploadedById: session?.user.id ?? '',
      },
    });

    revalidatePath(`/job-orders/${jobOrder.joNo}`);
  }

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-3">
              <h2 className="text-2xl font-bold text-slate-900">{jo.joNo}</h2>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-200">
                {jo.status}
              </span>
            </div>
            <p className="text-sm text-slate-500">
              {jo.customer.name} • {jo.vehicle.makeModel} ({jo.vehicle.plateNo})
            </p>
          </div>
          <div className="text-base font-bold font-mono text-slate-900">
            ₱{jo.billedAmount.toFixed(2)}
          </div>
        </div>

        <div className="pt-2">
          <StatusWorkflowStepper status={jo.status} />
        </div>

        {canManage && (
          <div className="border-t border-slate-200 pt-4 space-y-4">
            <form action={assignFormAction} className="flex items-end gap-2">
              <div className="flex-1">
                <label className="text-sm font-semibold text-slate-700">Technician</label>
                <input
                  name="technician"
                  defaultValue={jo.technician ?? ''}
                  placeholder="Assign technician"
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 text-base"
                />
              </div>
              <button
                type="submit"
                className="px-4 py-2 bg-slate-900 text-white rounded-xl text-sm font-semibold whitespace-nowrap h-9"
              >
                Assign
              </button>
            </form>

            <form action={statusFormAction} className="flex items-end gap-2">
              <div className="flex-1">
                <label className="text-sm font-semibold text-slate-700">Status</label>
                <select
                  name="nextStatus"
                  defaultValue={jo.status}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 text-base"
                >
                  {STATUS_OPTIONS.map((s) => (
                    <option key={s} value={s}>
                      {s}
                    </option>
                  ))}
                </select>
              </div>
              <button
                type="submit"
                className="px-4 py-2 bg-[#d32f2f] text-white rounded-xl text-sm font-semibold hover:bg-[#b71c1c] whitespace-nowrap h-9"
              >
                Update
              </button>
            </form>
          </div>
        )}
      </div>

      {canUpload && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
          <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center space-x-2">
            <Camera className="h-4 w-4" />
            <span>Attach Inspection Photo</span>
          </h3>
          <form action={photoFormAction} className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <input
              name="fileName"
              placeholder="File name"
              required
              className="px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <input
              name="storageKey"
              placeholder="B2 storage key"
              required
              className="px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <input
              name="contentType"
              placeholder="image/jpeg"
              defaultValue="image/jpeg"
              required
              className="px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <input
              name="size"
              type="number"
              placeholder="Size bytes"
              required
              className="px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <button
              type="submit"
              className="sm:col-span-4 px-4 py-2 bg-slate-900 text-white rounded-xl text-sm font-semibold hover:bg-slate-800 flex items-center justify-center space-x-1 whitespace-nowrap h-9"
            >
              <Plus className="h-4 w-4" />
              <span>Record Attachment</span>
            </button>
          </form>
          <p className="text-xs text-slate-400 mt-2">
            Actual B2 upload uses a client-side presigned URL. This form records the attachment
            metadata after upload.
          </p>
        </div>
      )}

      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-5 py-3 border-b border-slate-200 bg-slate-50">
          <h3 className="text-base font-bold text-slate-900">Event Timeline</h3>
        </div>
        <div className="p-5 space-y-3">
          {jo.events.map((event: (typeof jo.events)[number]) => (
            <div key={event.id} className="flex items-start space-x-3">
              <div className="w-2 h-2 mt-1.5 rounded-full bg-[#d32f2f]" />
              <div>
                <p className="text-sm font-semibold text-slate-800">{event.eventType}</p>
                <p className="text-sm text-slate-500">{event.description}</p>
                <p className="text-xs text-slate-400">
                  {new Date(event.createdAt).toLocaleString()}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {canManage && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
          <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center space-x-2">
            <CalendarDays className="h-4 w-4" />
            <span>Log Event</span>
          </h3>
          <form action={eventFormAction} className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <input
              name="eventType"
              placeholder="Event type (e.g. INSPECTION)"
              required
              className="px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <input
              name="description"
              placeholder="Description"
              required
              className="sm:col-span-2 px-3 py-2 rounded-xl border border-slate-300 text-base"
            />
            <button
              type="submit"
              className="px-4 py-2 bg-[#d32f2f] text-white rounded-xl text-sm font-semibold hover:bg-[#b71c1c] whitespace-nowrap h-9"
            >
              Add Event
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
