// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DisbursementStatus string

const (
	DisbursementStatusPENDING   DisbursementStatus = "PENDING"
	DisbursementStatusAPPROVED  DisbursementStatus = "APPROVED"
	DisbursementStatusPAID      DisbursementStatus = "PAID"
	DisbursementStatusCANCELLED DisbursementStatus = "CANCELLED"
)

func (e *DisbursementStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisbursementStatus(s)
	case string:
		*e = DisbursementStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisbursementStatus: %T", src)
	}
	return nil
}

type NullDisbursementStatus struct {
	DisbursementStatus DisbursementStatus `json:"disbursement_status"`
	Valid              bool               `json:"valid"` // Valid is true if DisbursementStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisbursementStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisbursementStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisbursementStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisbursementStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisbursementStatus), nil
}

type ItemType string

const (
	ItemTypeLABOR ItemType = "LABOR"
	ItemTypePARTS ItemType = "PARTS"
	ItemTypeMISC  ItemType = "MISC"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType `json:"item_type"`
	Valid    bool     `json:"valid"` // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type JoStatus string

const (
	JoStatusDRAFT        JoStatus = "DRAFT"
	JoStatusAPPROVED     JoStatus = "APPROVED"
	JoStatusINPROGRESS   JoStatus = "IN_PROGRESS"
	JoStatusPARTSPENDING JoStatus = "PARTS_PENDING"
	JoStatusCOMPLETED    JoStatus = "COMPLETED"
	JoStatusBILLED       JoStatus = "BILLED"
	JoStatusCLOSED       JoStatus = "CLOSED"
)

func (e *JoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JoStatus(s)
	case string:
		*e = JoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JoStatus: %T", src)
	}
	return nil
}

type NullJoStatus struct {
	JoStatus JoStatus `json:"jo_status"`
	Valid    bool     `json:"valid"` // Valid is true if JoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JoStatus), nil
}

type OpexStatus string

const (
	OpexStatusDRAFT           OpexStatus = "DRAFT"
	OpexStatusPENDINGAPPROVAL OpexStatus = "PENDING_APPROVAL"
	OpexStatusAPPROVED        OpexStatus = "APPROVED"
	OpexStatusREJECTED        OpexStatus = "REJECTED"
	OpexStatusDISBURSED       OpexStatus = "DISBURSED"
)

func (e *OpexStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OpexStatus(s)
	case string:
		*e = OpexStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OpexStatus: %T", src)
	}
	return nil
}

type NullOpexStatus struct {
	OpexStatus OpexStatus `json:"opex_status"`
	Valid      bool       `json:"valid"` // Valid is true if OpexStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOpexStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OpexStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OpexStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOpexStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OpexStatus), nil
}

type PoStatus string

const (
	PoStatusDRAFT    PoStatus = "DRAFT"
	PoStatusSENT     PoStatus = "SENT"
	PoStatusPARTIAL  PoStatus = "PARTIAL"
	PoStatusRECEIVED PoStatus = "RECEIVED"
	PoStatusCLOSED   PoStatus = "CLOSED"
)

func (e *PoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PoStatus(s)
	case string:
		*e = PoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PoStatus: %T", src)
	}
	return nil
}

type NullPoStatus struct {
	PoStatus PoStatus `json:"po_status"`
	Valid    bool     `json:"valid"` // Valid is true if PoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PoStatus), nil
}

type PrStatus string

const (
	PrStatusDRAFT           PrStatus = "DRAFT"
	PrStatusPENDINGAPPROVAL PrStatus = "PENDING_APPROVAL"
	PrStatusAPPROVED        PrStatus = "APPROVED"
	PrStatusREJECTED        PrStatus = "REJECTED"
	PrStatusCONVERTEDTOPO   PrStatus = "CONVERTED_TO_PO"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus `json:"pr_status"`
	Valid    bool     `json:"valid"` // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type QuoteStatus string

const (
	QuoteStatusDRAFT     QuoteStatus = "DRAFT"
	QuoteStatusAPPROVED  QuoteStatus = "APPROVED"
	QuoteStatusCONVERTED QuoteStatus = "CONVERTED"
	QuoteStatusREJECTED  QuoteStatus = "REJECTED"
)

func (e *QuoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuoteStatus(s)
	case string:
		*e = QuoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuoteStatus: %T", src)
	}
	return nil
}

type NullQuoteStatus struct {
	QuoteStatus QuoteStatus `json:"quote_status"`
	Valid       bool        `json:"valid"` // Valid is true if QuoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuoteStatus), nil
}

type ServiceInvoiceStatus string

const (
	ServiceInvoiceStatusDRAFT     ServiceInvoiceStatus = "DRAFT"
	ServiceInvoiceStatusSENT      ServiceInvoiceStatus = "SENT"
	ServiceInvoiceStatusPARTIAL   ServiceInvoiceStatus = "PARTIAL"
	ServiceInvoiceStatusPAID      ServiceInvoiceStatus = "PAID"
	ServiceInvoiceStatusCANCELLED ServiceInvoiceStatus = "CANCELLED"
)

func (e *ServiceInvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceInvoiceStatus(s)
	case string:
		*e = ServiceInvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceInvoiceStatus: %T", src)
	}
	return nil
}

type NullServiceInvoiceStatus struct {
	ServiceInvoiceStatus ServiceInvoiceStatus `json:"service_invoice_status"`
	Valid                bool                 `json:"valid"` // Valid is true if ServiceInvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceInvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceInvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceInvoiceStatus), nil
}

type SiStatus string

const (
	SiStatusDRAFT     SiStatus = "DRAFT"
	SiStatusALLOCATED SiStatus = "ALLOCATED"
	SiStatusAPPROVED  SiStatus = "APPROVED"
	SiStatusPAID      SiStatus = "PAID"
	SiStatusCANCELLED SiStatus = "CANCELLED"
)

func (e *SiStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SiStatus(s)
	case string:
		*e = SiStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SiStatus: %T", src)
	}
	return nil
}

type NullSiStatus struct {
	SiStatus SiStatus `json:"si_status"`
	Valid    bool     `json:"valid"` // Valid is true if SiStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSiStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SiStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SiStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSiStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SiStatus), nil
}

type Attachment struct {
	ID            string             `db:"id" json:"id"`
	EntityType    string             `db:"entity_type" json:"entity_type"`
	EntityID      string             `db:"entity_id" json:"entity_id"`
	FileName      string             `db:"file_name" json:"file_name"`
	ContentType   string             `db:"content_type" json:"content_type"`
	SizeBytes     int32              `db:"size_bytes" json:"size_bytes"`
	StorageKey    string             `db:"storage_key" json:"storage_key"`
	CreatedByRole *string            `db:"created_by_role" json:"created_by_role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Customer struct {
	ID         string             `db:"id" json:"id"`
	CustomerNo string             `db:"customer_no" json:"customer_no"`
	Name       string             `db:"name" json:"name"`
	Tin        *string            `db:"tin" json:"tin"`
	Address    *string            `db:"address" json:"address"`
	Phone      *string            `db:"phone" json:"phone"`
	Email      *string            `db:"email" json:"email"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Disbursement struct {
	ID                 string             `db:"id" json:"id"`
	DisbursementNo     string             `db:"disbursement_no" json:"disbursement_no"`
	OpexRequestID      *string            `db:"opex_request_id" json:"opex_request_id"`
	SupplierInvoiceID  *string            `db:"supplier_invoice_id" json:"supplier_invoice_id"`
	AmountCents        int64              `db:"amount_cents" json:"amount_cents"`
	Status             DisbursementStatus `db:"status" json:"status"`
	PaymentMethod      *string            `db:"payment_method" json:"payment_method"`
	ReferenceNo        *string            `db:"reference_no" json:"reference_no"`
	PaidAt             pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ProofAttachmentKey *string            `db:"proof_attachment_key" json:"proof_attachment_key"`
	RecordedByRole     *string            `db:"recorded_by_role" json:"recorded_by_role"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type JobOrder struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	CubeTopperNo             *string            `db:"cube_topper_no" json:"cube_topper_no"`
	PromisedDate             pgtype.Timestamptz `db:"promised_date" json:"promised_date"`
	PaymentMode              *string            `db:"payment_mode" json:"payment_mode"`
	InsurerLoa               *string            `db:"insurer_loa" json:"insurer_loa"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type JobOrderEvent struct {
	ID            string             `db:"id" json:"id"`
	JoID          string             `db:"jo_id" json:"jo_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Description   string             `db:"description" json:"description"`
	CreatedByRole *string            `db:"created_by_role" json:"created_by_role"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type JobOrderItem struct {
	ID             string   `db:"id" json:"id"`
	JoID           string   `db:"jo_id" json:"jo_id"`
	ItemType       ItemType `db:"item_type" json:"item_type"`
	Description    string   `db:"description" json:"description"`
	Quantity       float64  `db:"quantity" json:"quantity"`
	UnitPriceCents int64    `db:"unit_price_cents" json:"unit_price_cents"`
	DiscountCents  int64    `db:"discount_cents" json:"discount_cents"`
	NetAmountCents int64    `db:"net_amount_cents" json:"net_amount_cents"`
}

type OpexRequest struct {
	ID              string             `db:"id" json:"id"`
	RequestNo       string             `db:"request_no" json:"request_no"`
	Category        string             `db:"category" json:"category"`
	Description     string             `db:"description" json:"description"`
	AmountCents     int64              `db:"amount_cents" json:"amount_cents"`
	RequestedByRole string             `db:"requested_by_role" json:"requested_by_role"`
	Status          OpexStatus         `db:"status" json:"status"`
	RequestedAt     pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ApprovedByRole  *string            `db:"approved_by_role" json:"approved_by_role"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	Notes           *string            `db:"notes" json:"notes"`
}

type Payment struct {
	ID               string             `db:"id" json:"id"`
	ServiceInvoiceID string             `db:"service_invoice_id" json:"service_invoice_id"`
	AmountCents      int64              `db:"amount_cents" json:"amount_cents"`
	PaymentMethod    string             `db:"payment_method" json:"payment_method"`
	ReferenceNo      *string            `db:"reference_no" json:"reference_no"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	RecordedByRole   *string            `db:"recorded_by_role" json:"recorded_by_role"`
}

type PurchaseOrder struct {
	ID         string             `db:"id" json:"id"`
	PoNo       string             `db:"po_no" json:"po_no"`
	PrID       *string            `db:"pr_id" json:"pr_id"`
	Status     PoStatus           `db:"status" json:"status"`
	Supplier   *string            `db:"supplier" json:"supplier"`
	TotalCents int64              `db:"total_cents" json:"total_cents"`
	OrderedAt  pgtype.Timestamptz `db:"ordered_at" json:"ordered_at"`
	ReceivedAt pgtype.Timestamptz `db:"received_at" json:"received_at"`
	Notes      *string            `db:"notes" json:"notes"`
}

type PurchaseOrderItem struct {
	ID            string  `db:"id" json:"id"`
	PoID          string  `db:"po_id" json:"po_id"`
	Description   string  `db:"description" json:"description"`
	Quantity      float64 `db:"quantity" json:"quantity"`
	UnitCostCents int64   `db:"unit_cost_cents" json:"unit_cost_cents"`
	TotalCents    int64   `db:"total_cents" json:"total_cents"`
	ReceivedQty   float64 `db:"received_qty" json:"received_qty"`
}

type PurchaseRequest struct {
	ID              string             `db:"id" json:"id"`
	PrNo            string             `db:"pr_no" json:"pr_no"`
	JoID            *string            `db:"jo_id" json:"jo_id"`
	Status          PrStatus           `db:"status" json:"status"`
	RequestedByRole string             `db:"requested_by_role" json:"requested_by_role"`
	RequestedAt     pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ApprovedByRole  *string            `db:"approved_by_role" json:"approved_by_role"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	Supplier        *string            `db:"supplier" json:"supplier"`
	Notes           *string            `db:"notes" json:"notes"`
}

type PurchaseRequestItem struct {
	ID            string  `db:"id" json:"id"`
	PrID          string  `db:"pr_id" json:"pr_id"`
	Description   string  `db:"description" json:"description"`
	Quantity      float64 `db:"quantity" json:"quantity"`
	UnitCostCents int64   `db:"unit_cost_cents" json:"unit_cost_cents"`
	TotalCents    int64   `db:"total_cents" json:"total_cents"`
}

type SalesQuotation struct {
	ID              string             `db:"id" json:"id"`
	QuoteNo         string             `db:"quote_no" json:"quote_no"`
	CustomerID      string             `db:"customer_id" json:"customer_id"`
	VehicleID       string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor         string             `db:"advisor" json:"advisor"`
	TotalLaborCents int64              `db:"total_labor_cents" json:"total_labor_cents"`
	TotalPartsCents int64              `db:"total_parts_cents" json:"total_parts_cents"`
	NetTotalCents   int64              `db:"net_total_cents" json:"net_total_cents"`
	Status          QuoteStatus        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SalesQuotationItem struct {
	ID             string   `db:"id" json:"id"`
	QuoteID        string   `db:"quote_id" json:"quote_id"`
	ItemType       ItemType `db:"item_type" json:"item_type"`
	Description    string   `db:"description" json:"description"`
	Quantity       float64  `db:"quantity" json:"quantity"`
	UnitPriceCents int64    `db:"unit_price_cents" json:"unit_price_cents"`
	DiscountCents  int64    `db:"discount_cents" json:"discount_cents"`
	NetAmountCents int64    `db:"net_amount_cents" json:"net_amount_cents"`
}

type ServiceInvoice struct {
	ID              string               `db:"id" json:"id"`
	InvoiceNo       string               `db:"invoice_no" json:"invoice_no"`
	JoID            *string              `db:"jo_id" json:"jo_id"`
	CustomerID      string               `db:"customer_id" json:"customer_id"`
	IssueDate       pgtype.Date          `db:"issue_date" json:"issue_date"`
	SubtotalCents   int64                `db:"subtotal_cents" json:"subtotal_cents"`
	VatAmountCents  int64                `db:"vat_amount_cents" json:"vat_amount_cents"`
	TotalCents      int64                `db:"total_cents" json:"total_cents"`
	AmountPaidCents int64                `db:"amount_paid_cents" json:"amount_paid_cents"`
	Status          ServiceInvoiceStatus `db:"status" json:"status"`
	DueDate         pgtype.Date          `db:"due_date" json:"due_date"`
	Notes           *string              `db:"notes" json:"notes"`
}

type SupplierInvoice struct {
	ID               string      `db:"id" json:"id"`
	SiNo             string      `db:"si_no" json:"si_no"`
	PoID             *string     `db:"po_id" json:"po_id"`
	Supplier         *string     `db:"supplier" json:"supplier"`
	InvoiceDate      pgtype.Date `db:"invoice_date" json:"invoice_date"`
	DueDate          pgtype.Date `db:"due_date" json:"due_date"`
	TotalAmountCents int64       `db:"total_amount_cents" json:"total_amount_cents"`
	Status           SiStatus    `db:"status" json:"status"`
	Notes            *string     `db:"notes" json:"notes"`
}

type SupplierInvoiceAllocation struct {
	ID          string             `db:"id" json:"id"`
	SiID        string             `db:"si_id" json:"si_id"`
	JoID        string             `db:"jo_id" json:"jo_id"`
	AmountCents int64              `db:"amount_cents" json:"amount_cents"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Vehicle struct {
	ID         string             `db:"id" json:"id"`
	CustomerID string             `db:"customer_id" json:"customer_id"`
	PlateNo    string             `db:"plate_no" json:"plate_no"`
	VinChassis *string            `db:"vin_chassis" json:"vin_chassis"`
	EngineNo   *string            `db:"engine_no" json:"engine_no"`
	MakeModel  string             `db:"make_model" json:"make_model"`
	Year       *string            `db:"year" json:"year"`
	Color      *string            `db:"color" json:"color"`
	Odometer   *int32             `db:"odometer" json:"odometer"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
