// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDisbursement = `-- name: ApproveDisbursement :one
UPDATE disbursements
SET status = 'APPROVED'
WHERE id = $1
RETURNING id, disbursement_no, opex_request_id, supplier_invoice_id, amount_cents, status,
  payment_method, reference_no, paid_at, proof_attachment_key, recorded_by_role, created_at
`

func (q *Queries) ApproveDisbursement(ctx context.Context, id string) (Disbursement, error) {
	row := q.db.QueryRow(ctx, approveDisbursement, id)
	var i Disbursement
	err := row.Scan(
		&i.ID,
		&i.DisbursementNo,
		&i.OpexRequestID,
		&i.SupplierInvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.ProofAttachmentKey,
		&i.RecordedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const approveOpexRequest = `-- name: ApproveOpexRequest :one
UPDATE opex_requests
SET status = 'APPROVED', approved_by_role = $2, approved_at = now()
WHERE id = $1
RETURNING id, request_no, category, description, amount_cents, requested_by_role, status, requested_at, approved_by_role, approved_at, notes
`

type ApproveOpexRequestParams struct {
	ID             string  `db:"id" json:"id"`
	ApprovedByRole *string `db:"approved_by_role" json:"approved_by_role"`
}

func (q *Queries) ApproveOpexRequest(ctx context.Context, arg ApproveOpexRequestParams) (OpexRequest, error) {
	row := q.db.QueryRow(ctx, approveOpexRequest, arg.ID, arg.ApprovedByRole)
	var i OpexRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.Category,
		&i.Description,
		&i.AmountCents,
		&i.RequestedByRole,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Notes,
	)
	return i, err
}

const approvePurchaseRequest = `-- name: ApprovePurchaseRequest :one
UPDATE purchase_requests
SET status = 'APPROVED', approved_by_role = $2, approved_at = now()
WHERE id = $1
RETURNING id, pr_no, jo_id, status, requested_by_role, requested_at, approved_by_role, approved_at, supplier, notes
`

type ApprovePurchaseRequestParams struct {
	ID             string  `db:"id" json:"id"`
	ApprovedByRole *string `db:"approved_by_role" json:"approved_by_role"`
}

func (q *Queries) ApprovePurchaseRequest(ctx context.Context, arg ApprovePurchaseRequestParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, approvePurchaseRequest, arg.ID, arg.ApprovedByRole)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.PrNo,
		&i.JoID,
		&i.Status,
		&i.RequestedByRole,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Supplier,
		&i.Notes,
	)
	return i, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobOrders = `-- name: CountJobOrders :one
SELECT count(*) FROM job_orders
`

func (q *Queries) CountJobOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobOrdersByStatus = `-- name: CountJobOrdersByStatus :one
SELECT count(*) FROM job_orders WHERE status = $1
`

func (q *Queries) CountJobOrdersByStatus(ctx context.Context, status JoStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countJobOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpexRequestsPending = `-- name: CountOpexRequestsPending :one
SELECT count(*) FROM opex_requests WHERE status = 'PENDING_APPROVAL'
`

func (q *Queries) CountOpexRequestsPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpexRequestsPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrders = `-- name: CountPurchaseOrders :one
SELECT count(*) FROM purchase_orders
`

func (q *Queries) CountPurchaseOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseRequestsPending = `-- name: CountPurchaseRequestsPending :one
SELECT count(*) FROM purchase_requests WHERE status = 'PENDING_APPROVAL'
`

func (q *Queries) CountPurchaseRequestsPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseRequestsPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuotations = `-- name: CountQuotations :one
SELECT count(*) FROM sales_quotations
`

func (q *Queries) CountQuotations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuotationsByStatus = `-- name: CountQuotationsByStatus :one
SELECT count(*) FROM sales_quotations WHERE status = $1
`

func (q *Queries) CountQuotationsByStatus(ctx context.Context, status QuoteStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupplierInvoicesPending = `-- name: CountSupplierInvoicesPending :one
SELECT count(*) FROM supplier_invoices WHERE status = 'APPROVED'
`

func (q *Queries) CountSupplierInvoicesPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSupplierInvoicesPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVehiclesByCustomer = `-- name: CountVehiclesByCustomer :one
SELECT count(*) FROM vehicles WHERE customer_id = $1
`

func (q *Queries) CountVehiclesByCustomer(ctx context.Context, customerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countVehiclesByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (entity_type, entity_id, file_name, content_type, size_bytes, storage_key, created_by_role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, entity_type, entity_id, file_name, content_type, size_bytes, storage_key, created_by_role, created_at
`

type CreateAttachmentParams struct {
	EntityType    string  `db:"entity_type" json:"entity_type"`
	EntityID      string  `db:"entity_id" json:"entity_id"`
	FileName      string  `db:"file_name" json:"file_name"`
	ContentType   string  `db:"content_type" json:"content_type"`
	SizeBytes     int32   `db:"size_bytes" json:"size_bytes"`
	StorageKey    string  `db:"storage_key" json:"storage_key"`
	CreatedByRole *string `db:"created_by_role" json:"created_by_role"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.EntityType,
		arg.EntityID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.CreatedByRole,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (customer_no, name, tin, address, phone, email)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_no, name, tin, address, phone, email, created_at, updated_at
`

type CreateCustomerParams struct {
	CustomerNo string  `db:"customer_no" json:"customer_no"`
	Name       string  `db:"name" json:"name"`
	Tin        *string `db:"tin" json:"tin"`
	Address    *string `db:"address" json:"address"`
	Phone      *string `db:"phone" json:"phone"`
	Email      *string `db:"email" json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CustomerNo,
		arg.Name,
		arg.Tin,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerNo,
		&i.Name,
		&i.Tin,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDisbursementFromOpex = `-- name: CreateDisbursementFromOpex :one
INSERT INTO disbursements (disbursement_no, opex_request_id, amount_cents, status)
VALUES ($1, $2, $3, 'PENDING')
RETURNING id, disbursement_no, opex_request_id, supplier_invoice_id, amount_cents, status,
  payment_method, reference_no, paid_at, proof_attachment_key, recorded_by_role, created_at
`

type CreateDisbursementFromOpexParams struct {
	DisbursementNo string  `db:"disbursement_no" json:"disbursement_no"`
	OpexRequestID  *string `db:"opex_request_id" json:"opex_request_id"`
	AmountCents    int64   `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) CreateDisbursementFromOpex(ctx context.Context, arg CreateDisbursementFromOpexParams) (Disbursement, error) {
	row := q.db.QueryRow(ctx, createDisbursementFromOpex, arg.DisbursementNo, arg.OpexRequestID, arg.AmountCents)
	var i Disbursement
	err := row.Scan(
		&i.ID,
		&i.DisbursementNo,
		&i.OpexRequestID,
		&i.SupplierInvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.ProofAttachmentKey,
		&i.RecordedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const createDisbursementFromSupplierInvoice = `-- name: CreateDisbursementFromSupplierInvoice :one
INSERT INTO disbursements (disbursement_no, supplier_invoice_id, amount_cents, status)
VALUES ($1, $2, $3, 'PENDING')
RETURNING id, disbursement_no, opex_request_id, supplier_invoice_id, amount_cents, status,
  payment_method, reference_no, paid_at, proof_attachment_key, recorded_by_role, created_at
`

type CreateDisbursementFromSupplierInvoiceParams struct {
	DisbursementNo    string  `db:"disbursement_no" json:"disbursement_no"`
	SupplierInvoiceID *string `db:"supplier_invoice_id" json:"supplier_invoice_id"`
	AmountCents       int64   `db:"amount_cents" json:"amount_cents"`
}

func (q *Queries) CreateDisbursementFromSupplierInvoice(ctx context.Context, arg CreateDisbursementFromSupplierInvoiceParams) (Disbursement, error) {
	row := q.db.QueryRow(ctx, createDisbursementFromSupplierInvoice, arg.DisbursementNo, arg.SupplierInvoiceID, arg.AmountCents)
	var i Disbursement
	err := row.Scan(
		&i.ID,
		&i.DisbursementNo,
		&i.OpexRequestID,
		&i.SupplierInvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.ProofAttachmentKey,
		&i.RecordedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const createJobOrder = `-- name: CreateJobOrder :one
INSERT INTO job_orders (jo_no, sq_id, customer_id, vehicle_id, advisor, status,
  total_estimated_labor_cents, total_estimated_parts_cents)
VALUES ($1, $2, $3, $4, $5, 'IN_PROGRESS', $6, $7)
RETURNING id, jo_no, sq_id, customer_id, vehicle_id, advisor, technician, status,
  total_estimated_labor_cents, total_estimated_parts_cents, actual_labor_cost_cents,
  actual_parts_cost_cents, billed_amount_cents, net_profit_cents, created_at, updated_at
`

type CreateJobOrderParams struct {
	JoNo                     string  `db:"jo_no" json:"jo_no"`
	SqID                     *string `db:"sq_id" json:"sq_id"`
	CustomerID               string  `db:"customer_id" json:"customer_id"`
	VehicleID                string  `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string  `db:"advisor" json:"advisor"`
	TotalEstimatedLaborCents int64   `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64   `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
}

type CreateJobOrderRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateJobOrder(ctx context.Context, arg CreateJobOrderParams) (CreateJobOrderRow, error) {
	row := q.db.QueryRow(ctx, createJobOrder,
		arg.JoNo,
		arg.SqID,
		arg.CustomerID,
		arg.VehicleID,
		arg.Advisor,
		arg.TotalEstimatedLaborCents,
		arg.TotalEstimatedPartsCents,
	)
	var i CreateJobOrderRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobOrderEvent = `-- name: CreateJobOrderEvent :one
INSERT INTO job_order_events (jo_id, event_type, description, created_by_role)
VALUES ($1, $2, $3, $4)
RETURNING id, jo_id, event_type, description, created_by_role, created_at
`

type CreateJobOrderEventParams struct {
	JoID          string  `db:"jo_id" json:"jo_id"`
	EventType     string  `db:"event_type" json:"event_type"`
	Description   string  `db:"description" json:"description"`
	CreatedByRole *string `db:"created_by_role" json:"created_by_role"`
}

func (q *Queries) CreateJobOrderEvent(ctx context.Context, arg CreateJobOrderEventParams) (JobOrderEvent, error) {
	row := q.db.QueryRow(ctx, createJobOrderEvent,
		arg.JoID,
		arg.EventType,
		arg.Description,
		arg.CreatedByRole,
	)
	var i JobOrderEvent
	err := row.Scan(
		&i.ID,
		&i.JoID,
		&i.EventType,
		&i.Description,
		&i.CreatedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const createJobOrderItem = `-- name: CreateJobOrderItem :one
INSERT INTO job_order_items (jo_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, jo_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents
`

type CreateJobOrderItemParams struct {
	JoID           string   `db:"jo_id" json:"jo_id"`
	ItemType       ItemType `db:"item_type" json:"item_type"`
	Description    string   `db:"description" json:"description"`
	Quantity       float64  `db:"quantity" json:"quantity"`
	UnitPriceCents int64    `db:"unit_price_cents" json:"unit_price_cents"`
	DiscountCents  int64    `db:"discount_cents" json:"discount_cents"`
	NetAmountCents int64    `db:"net_amount_cents" json:"net_amount_cents"`
}

func (q *Queries) CreateJobOrderItem(ctx context.Context, arg CreateJobOrderItemParams) (JobOrderItem, error) {
	row := q.db.QueryRow(ctx, createJobOrderItem,
		arg.JoID,
		arg.ItemType,
		arg.Description,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.DiscountCents,
		arg.NetAmountCents,
	)
	var i JobOrderItem
	err := row.Scan(
		&i.ID,
		&i.JoID,
		&i.ItemType,
		&i.Description,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.DiscountCents,
		&i.NetAmountCents,
	)
	return i, err
}

const createOpexRequest = `-- name: CreateOpexRequest :one
INSERT INTO opex_requests (request_no, category, description, amount_cents, requested_by_role, status, notes)
VALUES ($1, $2, $3, $4, $5, 'PENDING_APPROVAL', $6)
RETURNING id, request_no, category, description, amount_cents, requested_by_role, status, requested_at, approved_by_role, approved_at, notes
`

type CreateOpexRequestParams struct {
	RequestNo       string  `db:"request_no" json:"request_no"`
	Category        string  `db:"category" json:"category"`
	Description     string  `db:"description" json:"description"`
	AmountCents     int64   `db:"amount_cents" json:"amount_cents"`
	RequestedByRole string  `db:"requested_by_role" json:"requested_by_role"`
	Notes           *string `db:"notes" json:"notes"`
}

func (q *Queries) CreateOpexRequest(ctx context.Context, arg CreateOpexRequestParams) (OpexRequest, error) {
	row := q.db.QueryRow(ctx, createOpexRequest,
		arg.RequestNo,
		arg.Category,
		arg.Description,
		arg.AmountCents,
		arg.RequestedByRole,
		arg.Notes,
	)
	var i OpexRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.Category,
		&i.Description,
		&i.AmountCents,
		&i.RequestedByRole,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Notes,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (service_invoice_id, amount_cents, payment_method, reference_no, paid_at, recorded_by_role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_invoice_id, amount_cents, payment_method, reference_no, paid_at, recorded_by_role
`

type CreatePaymentParams struct {
	ServiceInvoiceID string             `db:"service_invoice_id" json:"service_invoice_id"`
	AmountCents      int64              `db:"amount_cents" json:"amount_cents"`
	PaymentMethod    string             `db:"payment_method" json:"payment_method"`
	ReferenceNo      *string            `db:"reference_no" json:"reference_no"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	RecordedByRole   *string            `db:"recorded_by_role" json:"recorded_by_role"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ServiceInvoiceID,
		arg.AmountCents,
		arg.PaymentMethod,
		arg.ReferenceNo,
		arg.PaidAt,
		arg.RecordedByRole,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ServiceInvoiceID,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.RecordedByRole,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (po_no, pr_id, status, supplier, total_cents)
VALUES ($1, $2, 'DRAFT', $3, $4)
RETURNING id, po_no, pr_id, status, supplier, total_cents, ordered_at, received_at, notes
`

type CreatePurchaseOrderParams struct {
	PoNo       string  `db:"po_no" json:"po_no"`
	PrID       *string `db:"pr_id" json:"pr_id"`
	Supplier   *string `db:"supplier" json:"supplier"`
	TotalCents int64   `db:"total_cents" json:"total_cents"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.PoNo,
		arg.PrID,
		arg.Supplier,
		arg.TotalCents,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.PrID,
		&i.Status,
		&i.Supplier,
		&i.TotalCents,
		&i.OrderedAt,
		&i.ReceivedAt,
		&i.Notes,
	)
	return i, err
}

const createPurchaseOrderItem = `-- name: CreatePurchaseOrderItem :one
INSERT INTO purchase_order_items (po_id, description, quantity, unit_cost_cents, total_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, po_id, description, quantity, unit_cost_cents, total_cents, received_qty
`

type CreatePurchaseOrderItemParams struct {
	PoID          string  `db:"po_id" json:"po_id"`
	Description   string  `db:"description" json:"description"`
	Quantity      float64 `db:"quantity" json:"quantity"`
	UnitCostCents int64   `db:"unit_cost_cents" json:"unit_cost_cents"`
	TotalCents    int64   `db:"total_cents" json:"total_cents"`
}

func (q *Queries) CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderItem,
		arg.PoID,
		arg.Description,
		arg.Quantity,
		arg.UnitCostCents,
		arg.TotalCents,
	)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.Description,
		&i.Quantity,
		&i.UnitCostCents,
		&i.TotalCents,
		&i.ReceivedQty,
	)
	return i, err
}

const createPurchaseRequest = `-- name: CreatePurchaseRequest :one
INSERT INTO purchase_requests (pr_no, jo_id, status, requested_by_role, supplier, notes)
VALUES ($1, $2, 'PENDING_APPROVAL', $3, $4, $5)
RETURNING id, pr_no, jo_id, status, requested_by_role, requested_at, approved_by_role, approved_at, supplier, notes
`

type CreatePurchaseRequestParams struct {
	PrNo            string  `db:"pr_no" json:"pr_no"`
	JoID            *string `db:"jo_id" json:"jo_id"`
	RequestedByRole string  `db:"requested_by_role" json:"requested_by_role"`
	Supplier        *string `db:"supplier" json:"supplier"`
	Notes           *string `db:"notes" json:"notes"`
}

func (q *Queries) CreatePurchaseRequest(ctx context.Context, arg CreatePurchaseRequestParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequest,
		arg.PrNo,
		arg.JoID,
		arg.RequestedByRole,
		arg.Supplier,
		arg.Notes,
	)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.PrNo,
		&i.JoID,
		&i.Status,
		&i.RequestedByRole,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Supplier,
		&i.Notes,
	)
	return i, err
}

const createPurchaseRequestItem = `-- name: CreatePurchaseRequestItem :one
INSERT INTO purchase_request_items (pr_id, description, quantity, unit_cost_cents, total_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pr_id, description, quantity, unit_cost_cents, total_cents
`

type CreatePurchaseRequestItemParams struct {
	PrID          string  `db:"pr_id" json:"pr_id"`
	Description   string  `db:"description" json:"description"`
	Quantity      float64 `db:"quantity" json:"quantity"`
	UnitCostCents int64   `db:"unit_cost_cents" json:"unit_cost_cents"`
	TotalCents    int64   `db:"total_cents" json:"total_cents"`
}

func (q *Queries) CreatePurchaseRequestItem(ctx context.Context, arg CreatePurchaseRequestItemParams) (PurchaseRequestItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequestItem,
		arg.PrID,
		arg.Description,
		arg.Quantity,
		arg.UnitCostCents,
		arg.TotalCents,
	)
	var i PurchaseRequestItem
	err := row.Scan(
		&i.ID,
		&i.PrID,
		&i.Description,
		&i.Quantity,
		&i.UnitCostCents,
		&i.TotalCents,
	)
	return i, err
}

const createQuotationItem = `-- name: CreateQuotationItem :one
INSERT INTO sales_quotation_items (quote_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, quote_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents
`

type CreateQuotationItemParams struct {
	QuoteID        string   `db:"quote_id" json:"quote_id"`
	ItemType       ItemType `db:"item_type" json:"item_type"`
	Description    string   `db:"description" json:"description"`
	Quantity       float64  `db:"quantity" json:"quantity"`
	UnitPriceCents int64    `db:"unit_price_cents" json:"unit_price_cents"`
	DiscountCents  int64    `db:"discount_cents" json:"discount_cents"`
	NetAmountCents int64    `db:"net_amount_cents" json:"net_amount_cents"`
}

func (q *Queries) CreateQuotationItem(ctx context.Context, arg CreateQuotationItemParams) (SalesQuotationItem, error) {
	row := q.db.QueryRow(ctx, createQuotationItem,
		arg.QuoteID,
		arg.ItemType,
		arg.Description,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.DiscountCents,
		arg.NetAmountCents,
	)
	var i SalesQuotationItem
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.ItemType,
		&i.Description,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.DiscountCents,
		&i.NetAmountCents,
	)
	return i, err
}

const createSalesQuotation = `-- name: CreateSalesQuotation :one
INSERT INTO sales_quotations (quote_no, customer_id, vehicle_id, advisor, total_labor_cents, total_parts_cents, net_total_cents, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'DRAFT')
RETURNING id, quote_no, customer_id, vehicle_id, advisor, total_labor_cents, total_parts_cents, net_total_cents, status, created_at, updated_at
`

type CreateSalesQuotationParams struct {
	QuoteNo         string `db:"quote_no" json:"quote_no"`
	CustomerID      string `db:"customer_id" json:"customer_id"`
	VehicleID       string `db:"vehicle_id" json:"vehicle_id"`
	Advisor         string `db:"advisor" json:"advisor"`
	TotalLaborCents int64  `db:"total_labor_cents" json:"total_labor_cents"`
	TotalPartsCents int64  `db:"total_parts_cents" json:"total_parts_cents"`
	NetTotalCents   int64  `db:"net_total_cents" json:"net_total_cents"`
}

func (q *Queries) CreateSalesQuotation(ctx context.Context, arg CreateSalesQuotationParams) (SalesQuotation, error) {
	row := q.db.QueryRow(ctx, createSalesQuotation,
		arg.QuoteNo,
		arg.CustomerID,
		arg.VehicleID,
		arg.Advisor,
		arg.TotalLaborCents,
		arg.TotalPartsCents,
		arg.NetTotalCents,
	)
	var i SalesQuotation
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.TotalLaborCents,
		&i.TotalPartsCents,
		&i.NetTotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceInvoice = `-- name: CreateServiceInvoice :one
INSERT INTO service_invoices (invoice_no, jo_id, customer_id, subtotal_cents, vat_amount_cents, total_cents, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, 'SENT', $7)
RETURNING id, invoice_no, jo_id, customer_id, issue_date, subtotal_cents, vat_amount_cents,
  total_cents, amount_paid_cents, status, due_date, notes
`

type CreateServiceInvoiceParams struct {
	InvoiceNo      string  `db:"invoice_no" json:"invoice_no"`
	JoID           *string `db:"jo_id" json:"jo_id"`
	CustomerID     string  `db:"customer_id" json:"customer_id"`
	SubtotalCents  int64   `db:"subtotal_cents" json:"subtotal_cents"`
	VatAmountCents int64   `db:"vat_amount_cents" json:"vat_amount_cents"`
	TotalCents     int64   `db:"total_cents" json:"total_cents"`
	Notes          *string `db:"notes" json:"notes"`
}

func (q *Queries) CreateServiceInvoice(ctx context.Context, arg CreateServiceInvoiceParams) (ServiceInvoice, error) {
	row := q.db.QueryRow(ctx, createServiceInvoice,
		arg.InvoiceNo,
		arg.JoID,
		arg.CustomerID,
		arg.SubtotalCents,
		arg.VatAmountCents,
		arg.TotalCents,
		arg.Notes,
	)
	var i ServiceInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.JoID,
		&i.CustomerID,
		&i.IssueDate,
		&i.SubtotalCents,
		&i.VatAmountCents,
		&i.TotalCents,
		&i.AmountPaidCents,
		&i.Status,
		&i.DueDate,
		&i.Notes,
	)
	return i, err
}

const createSupplierInvoice = `-- name: CreateSupplierInvoice :one
INSERT INTO supplier_invoices (si_no, po_id, supplier, invoice_date, due_date, total_amount_cents, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, 'DRAFT', $7)
RETURNING id, si_no, po_id, supplier, invoice_date, due_date, total_amount_cents, status, notes
`

type CreateSupplierInvoiceParams struct {
	SiNo             string      `db:"si_no" json:"si_no"`
	PoID             *string     `db:"po_id" json:"po_id"`
	Supplier         *string     `db:"supplier" json:"supplier"`
	InvoiceDate      pgtype.Date `db:"invoice_date" json:"invoice_date"`
	DueDate          pgtype.Date `db:"due_date" json:"due_date"`
	TotalAmountCents int64       `db:"total_amount_cents" json:"total_amount_cents"`
	Notes            *string     `db:"notes" json:"notes"`
}

func (q *Queries) CreateSupplierInvoice(ctx context.Context, arg CreateSupplierInvoiceParams) (SupplierInvoice, error) {
	row := q.db.QueryRow(ctx, createSupplierInvoice,
		arg.SiNo,
		arg.PoID,
		arg.Supplier,
		arg.InvoiceDate,
		arg.DueDate,
		arg.TotalAmountCents,
		arg.Notes,
	)
	var i SupplierInvoice
	err := row.Scan(
		&i.ID,
		&i.SiNo,
		&i.PoID,
		&i.Supplier,
		&i.InvoiceDate,
		&i.DueDate,
		&i.TotalAmountCents,
		&i.Status,
		&i.Notes,
	)
	return i, err
}

const createSupplierInvoiceAllocation = `-- name: CreateSupplierInvoiceAllocation :one
INSERT INTO supplier_invoice_allocations (si_id, jo_id, amount_cents, description)
VALUES ($1, $2, $3, $4)
RETURNING id, si_id, jo_id, amount_cents, description, created_at
`

type CreateSupplierInvoiceAllocationParams struct {
	SiID        string  `db:"si_id" json:"si_id"`
	JoID        string  `db:"jo_id" json:"jo_id"`
	AmountCents int64   `db:"amount_cents" json:"amount_cents"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) CreateSupplierInvoiceAllocation(ctx context.Context, arg CreateSupplierInvoiceAllocationParams) (SupplierInvoiceAllocation, error) {
	row := q.db.QueryRow(ctx, createSupplierInvoiceAllocation,
		arg.SiID,
		arg.JoID,
		arg.AmountCents,
		arg.Description,
	)
	var i SupplierInvoiceAllocation
	err := row.Scan(
		&i.ID,
		&i.SiID,
		&i.JoID,
		&i.AmountCents,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer, created_at, updated_at
`

type CreateVehicleParams struct {
	CustomerID string  `db:"customer_id" json:"customer_id"`
	PlateNo    string  `db:"plate_no" json:"plate_no"`
	VinChassis *string `db:"vin_chassis" json:"vin_chassis"`
	EngineNo   *string `db:"engine_no" json:"engine_no"`
	MakeModel  string  `db:"make_model" json:"make_model"`
	Year       *string `db:"year" json:"year"`
	Color      *string `db:"color" json:"color"`
	Odometer   *int32  `db:"odometer" json:"odometer"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.CustomerID,
		arg.PlateNo,
		arg.VinChassis,
		arg.EngineNo,
		arg.MakeModel,
		arg.Year,
		arg.Color,
		arg.Odometer,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlateNo,
		&i.VinChassis,
		&i.EngineNo,
		&i.MakeModel,
		&i.Year,
		&i.Color,
		&i.Odometer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllData = `-- name: DeleteAllData :exec
TRUNCATE customers, vehicles, sales_quotations, sales_quotation_items, job_orders, job_order_items,
  job_order_events, attachments, purchase_requests, purchase_request_items, purchase_orders,
  purchase_order_items, supplier_invoices, supplier_invoice_allocations, opex_requests,
  disbursements, service_invoices, payments
RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllData)
	return err
}

const deleteSupplierInvoiceAllocations = `-- name: DeleteSupplierInvoiceAllocations :exec
DELETE FROM supplier_invoice_allocations WHERE si_id = $1
`

func (q *Queries) DeleteSupplierInvoiceAllocations(ctx context.Context, siID string) error {
	_, err := q.db.Exec(ctx, deleteSupplierInvoiceAllocations, siID)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, customer_no, name, tin, address, phone, email, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerNo,
		&i.Name,
		&i.Tin,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByNo = `-- name: GetCustomerByNo :one
SELECT id, customer_no, name, tin, address, phone, email, created_at, updated_at
FROM customers
WHERE customer_no = $1
`

func (q *Queries) GetCustomerByNo(ctx context.Context, customerNo string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByNo, customerNo)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerNo,
		&i.Name,
		&i.Tin,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisbursement = `-- name: GetDisbursement :one
SELECT id, disbursement_no, opex_request_id, supplier_invoice_id, amount_cents, status,
       payment_method, reference_no, paid_at, proof_attachment_key, recorded_by_role, created_at
FROM disbursements
WHERE id = $1
`

func (q *Queries) GetDisbursement(ctx context.Context, id string) (Disbursement, error) {
	row := q.db.QueryRow(ctx, getDisbursement, id)
	var i Disbursement
	err := row.Scan(
		&i.ID,
		&i.DisbursementNo,
		&i.OpexRequestID,
		&i.SupplierInvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.ProofAttachmentKey,
		&i.RecordedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const getJobOrder = `-- name: GetJobOrder :one
SELECT jo.id, jo.jo_no, jo.sq_id, jo.customer_id, jo.vehicle_id, jo.advisor,
       jo.technician, jo.status,
       jo.total_estimated_labor_cents, jo.total_estimated_parts_cents,
       jo.actual_labor_cost_cents, jo.actual_parts_cost_cents, jo.billed_amount_cents, jo.net_profit_cents,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       jo.created_at, jo.updated_at
FROM job_orders jo
JOIN customers c ON c.id = jo.customer_id
JOIN vehicles v ON v.id = jo.vehicle_id
WHERE jo.id = $1
`

type GetJobOrderRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CustomerName             string             `db:"customer_name" json:"customer_name"`
	VehiclePlate             string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel         string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetJobOrder(ctx context.Context, id string) (GetJobOrderRow, error) {
	row := q.db.QueryRow(ctx, getJobOrder, id)
	var i GetJobOrderRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CustomerName,
		&i.VehiclePlate,
		&i.VehicleMakeModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobOrderByNo = `-- name: GetJobOrderByNo :one
SELECT jo.id, jo.jo_no, jo.sq_id, jo.customer_id, jo.vehicle_id, jo.advisor,
       jo.technician, jo.status,
       jo.total_estimated_labor_cents, jo.total_estimated_parts_cents,
       jo.actual_labor_cost_cents, jo.actual_parts_cost_cents, jo.billed_amount_cents, jo.net_profit_cents,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       jo.created_at, jo.updated_at
FROM job_orders jo
JOIN customers c ON c.id = jo.customer_id
JOIN vehicles v ON v.id = jo.vehicle_id
WHERE jo.jo_no = $1
`

type GetJobOrderByNoRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CustomerName             string             `db:"customer_name" json:"customer_name"`
	VehiclePlate             string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel         string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetJobOrderByNo(ctx context.Context, joNo string) (GetJobOrderByNoRow, error) {
	row := q.db.QueryRow(ctx, getJobOrderByNo, joNo)
	var i GetJobOrderByNoRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CustomerName,
		&i.VehiclePlate,
		&i.VehicleMakeModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpexRequest = `-- name: GetOpexRequest :one
SELECT id, request_no, category, description, amount_cents, requested_by_role,
       status, requested_at, approved_by_role, approved_at, notes
FROM opex_requests
WHERE id = $1
`

func (q *Queries) GetOpexRequest(ctx context.Context, id string) (OpexRequest, error) {
	row := q.db.QueryRow(ctx, getOpexRequest, id)
	var i OpexRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.Category,
		&i.Description,
		&i.AmountCents,
		&i.RequestedByRole,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Notes,
	)
	return i, err
}

const getPurchaseRequest = `-- name: GetPurchaseRequest :one
SELECT pr.id, pr.pr_no, pr.jo_id, pr.status, pr.requested_by_role, pr.requested_at,
       pr.approved_by_role, pr.approved_at, pr.supplier, pr.notes,
       jo.jo_no AS job_order_no
FROM purchase_requests pr
LEFT JOIN job_orders jo ON jo.id = pr.jo_id
WHERE pr.id = $1
`

type GetPurchaseRequestRow struct {
	ID              string             `db:"id" json:"id"`
	PrNo            string             `db:"pr_no" json:"pr_no"`
	JoID            *string            `db:"jo_id" json:"jo_id"`
	Status          PrStatus           `db:"status" json:"status"`
	RequestedByRole string             `db:"requested_by_role" json:"requested_by_role"`
	RequestedAt     pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ApprovedByRole  *string            `db:"approved_by_role" json:"approved_by_role"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	Supplier        *string            `db:"supplier" json:"supplier"`
	Notes           *string            `db:"notes" json:"notes"`
	JobOrderNo      *string            `db:"job_order_no" json:"job_order_no"`
}

func (q *Queries) GetPurchaseRequest(ctx context.Context, id string) (GetPurchaseRequestRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseRequest, id)
	var i GetPurchaseRequestRow
	err := row.Scan(
		&i.ID,
		&i.PrNo,
		&i.JoID,
		&i.Status,
		&i.RequestedByRole,
		&i.RequestedAt,
		&i.ApprovedByRole,
		&i.ApprovedAt,
		&i.Supplier,
		&i.Notes,
		&i.JobOrderNo,
	)
	return i, err
}

const getSalesQuotation = `-- name: GetSalesQuotation :one
SELECT sq.id, sq.quote_no, sq.customer_id, sq.vehicle_id, sq.advisor,
       sq.total_labor_cents, sq.total_parts_cents, sq.net_total_cents, sq.status,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       sq.created_at, sq.updated_at
FROM sales_quotations sq
JOIN customers c ON c.id = sq.customer_id
JOIN vehicles v ON v.id = sq.vehicle_id
WHERE sq.id = $1
`

type GetSalesQuotationRow struct {
	ID               string             `db:"id" json:"id"`
	QuoteNo          string             `db:"quote_no" json:"quote_no"`
	CustomerID       string             `db:"customer_id" json:"customer_id"`
	VehicleID        string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor          string             `db:"advisor" json:"advisor"`
	TotalLaborCents  int64              `db:"total_labor_cents" json:"total_labor_cents"`
	TotalPartsCents  int64              `db:"total_parts_cents" json:"total_parts_cents"`
	NetTotalCents    int64              `db:"net_total_cents" json:"net_total_cents"`
	Status           QuoteStatus        `db:"status" json:"status"`
	CustomerName     string             `db:"customer_name" json:"customer_name"`
	VehiclePlate     string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSalesQuotation(ctx context.Context, id string) (GetSalesQuotationRow, error) {
	row := q.db.QueryRow(ctx, getSalesQuotation, id)
	var i GetSalesQuotationRow
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.TotalLaborCents,
		&i.TotalPartsCents,
		&i.NetTotalCents,
		&i.Status,
		&i.CustomerName,
		&i.VehiclePlate,
		&i.VehicleMakeModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceInvoice = `-- name: GetServiceInvoice :one
SELECT si.id, si.invoice_no, si.jo_id, si.customer_id, si.issue_date,
       si.subtotal_cents, si.vat_amount_cents, si.total_cents, si.amount_paid_cents,
       si.status, si.due_date, si.notes,
       c.name AS customer_name, jo.jo_no AS job_order_no
FROM service_invoices si
JOIN customers c ON c.id = si.customer_id
LEFT JOIN job_orders jo ON jo.id = si.jo_id
WHERE si.id = $1
`

type GetServiceInvoiceRow struct {
	ID              string               `db:"id" json:"id"`
	InvoiceNo       string               `db:"invoice_no" json:"invoice_no"`
	JoID            *string              `db:"jo_id" json:"jo_id"`
	CustomerID      string               `db:"customer_id" json:"customer_id"`
	IssueDate       pgtype.Date          `db:"issue_date" json:"issue_date"`
	SubtotalCents   int64                `db:"subtotal_cents" json:"subtotal_cents"`
	VatAmountCents  int64                `db:"vat_amount_cents" json:"vat_amount_cents"`
	TotalCents      int64                `db:"total_cents" json:"total_cents"`
	AmountPaidCents int64                `db:"amount_paid_cents" json:"amount_paid_cents"`
	Status          ServiceInvoiceStatus `db:"status" json:"status"`
	DueDate         pgtype.Date          `db:"due_date" json:"due_date"`
	Notes           *string              `db:"notes" json:"notes"`
	CustomerName    string               `db:"customer_name" json:"customer_name"`
	JobOrderNo      *string              `db:"job_order_no" json:"job_order_no"`
}

func (q *Queries) GetServiceInvoice(ctx context.Context, id string) (GetServiceInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getServiceInvoice, id)
	var i GetServiceInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.JoID,
		&i.CustomerID,
		&i.IssueDate,
		&i.SubtotalCents,
		&i.VatAmountCents,
		&i.TotalCents,
		&i.AmountPaidCents,
		&i.Status,
		&i.DueDate,
		&i.Notes,
		&i.CustomerName,
		&i.JobOrderNo,
	)
	return i, err
}

const getSupplierInvoice = `-- name: GetSupplierInvoice :one
SELECT id, si_no, po_id, supplier, invoice_date, due_date, total_amount_cents, status, notes
FROM supplier_invoices
WHERE id = $1
`

func (q *Queries) GetSupplierInvoice(ctx context.Context, id string) (SupplierInvoice, error) {
	row := q.db.QueryRow(ctx, getSupplierInvoice, id)
	var i SupplierInvoice
	err := row.Scan(
		&i.ID,
		&i.SiNo,
		&i.PoID,
		&i.Supplier,
		&i.InvoiceDate,
		&i.DueDate,
		&i.TotalAmountCents,
		&i.Status,
		&i.Notes,
	)
	return i, err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer, created_at, updated_at
FROM vehicles
WHERE id = $1
`

func (q *Queries) GetVehicle(ctx context.Context, id string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlateNo,
		&i.VinChassis,
		&i.EngineNo,
		&i.MakeModel,
		&i.Year,
		&i.Color,
		&i.Odometer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByPlate = `-- name: GetVehicleByPlate :one
SELECT id, customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer, created_at, updated_at
FROM vehicles
WHERE plate_no = $1
`

func (q *Queries) GetVehicleByPlate(ctx context.Context, plateNo string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByPlate, plateNo)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlateNo,
		&i.VinChassis,
		&i.EngineNo,
		&i.MakeModel,
		&i.Year,
		&i.Color,
		&i.Odometer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, entity_type, entity_id, file_name, content_type, size_bytes, storage_key, created_by_role, created_at
FROM attachments
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at
`

type ListAttachmentsParams struct {
	EntityType string `db:"entity_type" json:"entity_type"`
	EntityID   string `db:"entity_id" json:"entity_id"`
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedByRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, customer_no, name, tin, address, phone, email, created_at, updated_at
FROM customers
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CustomerNo,
			&i.Name,
			&i.Tin,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisbursements = `-- name: ListDisbursements :many
SELECT d.id, d.disbursement_no, d.opex_request_id, d.supplier_invoice_id,
       d.amount_cents, d.status, d.payment_method, d.reference_no, d.paid_at,
       d.proof_attachment_key, d.recorded_by_role, d.created_at,
       o.request_no AS opex_request_no, si.si_no AS supplier_invoice_no
FROM disbursements d
LEFT JOIN opex_requests o ON o.id = d.opex_request_id
LEFT JOIN supplier_invoices si ON si.id = d.supplier_invoice_id
ORDER BY d.created_at DESC
`

type ListDisbursementsRow struct {
	ID                 string             `db:"id" json:"id"`
	DisbursementNo     string             `db:"disbursement_no" json:"disbursement_no"`
	OpexRequestID      *string            `db:"opex_request_id" json:"opex_request_id"`
	SupplierInvoiceID  *string            `db:"supplier_invoice_id" json:"supplier_invoice_id"`
	AmountCents        int64              `db:"amount_cents" json:"amount_cents"`
	Status             DisbursementStatus `db:"status" json:"status"`
	PaymentMethod      *string            `db:"payment_method" json:"payment_method"`
	ReferenceNo        *string            `db:"reference_no" json:"reference_no"`
	PaidAt             pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ProofAttachmentKey *string            `db:"proof_attachment_key" json:"proof_attachment_key"`
	RecordedByRole     *string            `db:"recorded_by_role" json:"recorded_by_role"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	OpexRequestNo      *string            `db:"opex_request_no" json:"opex_request_no"`
	SupplierInvoiceNo  *string            `db:"supplier_invoice_no" json:"supplier_invoice_no"`
}

func (q *Queries) ListDisbursements(ctx context.Context) ([]ListDisbursementsRow, error) {
	rows, err := q.db.Query(ctx, listDisbursements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisbursementsRow
	for rows.Next() {
		var i ListDisbursementsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisbursementNo,
			&i.OpexRequestID,
			&i.SupplierInvoiceID,
			&i.AmountCents,
			&i.Status,
			&i.PaymentMethod,
			&i.ReferenceNo,
			&i.PaidAt,
			&i.ProofAttachmentKey,
			&i.RecordedByRole,
			&i.CreatedAt,
			&i.OpexRequestNo,
			&i.SupplierInvoiceNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOrderEvents = `-- name: ListJobOrderEvents :many
SELECT id, jo_id, event_type, description, created_by_role, created_at
FROM job_order_events
WHERE jo_id = $1
ORDER BY created_at
`

func (q *Queries) ListJobOrderEvents(ctx context.Context, joID string) ([]JobOrderEvent, error) {
	rows, err := q.db.Query(ctx, listJobOrderEvents, joID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobOrderEvent
	for rows.Next() {
		var i JobOrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.JoID,
			&i.EventType,
			&i.Description,
			&i.CreatedByRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOrderItems = `-- name: ListJobOrderItems :many
SELECT id, jo_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents
FROM job_order_items
WHERE jo_id = $1
`

func (q *Queries) ListJobOrderItems(ctx context.Context, joID string) ([]JobOrderItem, error) {
	rows, err := q.db.Query(ctx, listJobOrderItems, joID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobOrderItem
	for rows.Next() {
		var i JobOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.JoID,
			&i.ItemType,
			&i.Description,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.DiscountCents,
			&i.NetAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOrders = `-- name: ListJobOrders :many
SELECT jo.id, jo.jo_no, jo.sq_id, jo.customer_id, jo.vehicle_id, jo.advisor,
       jo.technician, jo.status,
       jo.total_estimated_labor_cents, jo.total_estimated_parts_cents,
       jo.actual_labor_cost_cents, jo.actual_parts_cost_cents, jo.billed_amount_cents, jo.net_profit_cents,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       jo.created_at, jo.updated_at
FROM job_orders jo
JOIN customers c ON c.id = jo.customer_id
JOIN vehicles v ON v.id = jo.vehicle_id
ORDER BY jo.created_at DESC
`

type ListJobOrdersRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CustomerName             string             `db:"customer_name" json:"customer_name"`
	VehiclePlate             string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel         string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListJobOrders(ctx context.Context) ([]ListJobOrdersRow, error) {
	rows, err := q.db.Query(ctx, listJobOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobOrdersRow
	for rows.Next() {
		var i ListJobOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.JoNo,
			&i.SqID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Advisor,
			&i.Technician,
			&i.Status,
			&i.TotalEstimatedLaborCents,
			&i.TotalEstimatedPartsCents,
			&i.ActualLaborCostCents,
			&i.ActualPartsCostCents,
			&i.BilledAmountCents,
			&i.NetProfitCents,
			&i.CustomerName,
			&i.VehiclePlate,
			&i.VehicleMakeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobOrdersByCustomer = `-- name: ListJobOrdersByCustomer :many
SELECT jo.id, jo.jo_no, jo.sq_id, jo.customer_id, jo.vehicle_id, jo.advisor,
       jo.technician, jo.status,
       jo.total_estimated_labor_cents, jo.total_estimated_parts_cents,
       jo.actual_labor_cost_cents, jo.actual_parts_cost_cents, jo.billed_amount_cents, jo.net_profit_cents,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       jo.created_at, jo.updated_at
FROM job_orders jo
JOIN customers c ON c.id = jo.customer_id
JOIN vehicles v ON v.id = jo.vehicle_id
WHERE jo.customer_id = $1
ORDER BY jo.created_at DESC
`

type ListJobOrdersByCustomerRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CustomerName             string             `db:"customer_name" json:"customer_name"`
	VehiclePlate             string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel         string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListJobOrdersByCustomer(ctx context.Context, customerID string) ([]ListJobOrdersByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listJobOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobOrdersByCustomerRow
	for rows.Next() {
		var i ListJobOrdersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.JoNo,
			&i.SqID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Advisor,
			&i.Technician,
			&i.Status,
			&i.TotalEstimatedLaborCents,
			&i.TotalEstimatedPartsCents,
			&i.ActualLaborCostCents,
			&i.ActualPartsCostCents,
			&i.BilledAmountCents,
			&i.NetProfitCents,
			&i.CustomerName,
			&i.VehiclePlate,
			&i.VehicleMakeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpexRequests = `-- name: ListOpexRequests :many
SELECT id, request_no, category, description, amount_cents, requested_by_role,
       status, requested_at, approved_by_role, approved_at, notes
FROM opex_requests
ORDER BY requested_at DESC
`

func (q *Queries) ListOpexRequests(ctx context.Context) ([]OpexRequest, error) {
	rows, err := q.db.Query(ctx, listOpexRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpexRequest
	for rows.Next() {
		var i OpexRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestNo,
			&i.Category,
			&i.Description,
			&i.AmountCents,
			&i.RequestedByRole,
			&i.Status,
			&i.RequestedAt,
			&i.ApprovedByRole,
			&i.ApprovedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, service_invoice_id, amount_cents, payment_method, reference_no, paid_at, recorded_by_role
FROM payments
WHERE service_invoice_id = $1
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, serviceInvoiceID string) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, serviceInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceInvoiceID,
			&i.AmountCents,
			&i.PaymentMethod,
			&i.ReferenceNo,
			&i.PaidAt,
			&i.RecordedByRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseRequestItems = `-- name: ListPurchaseRequestItems :many
SELECT id, pr_id, description, quantity, unit_cost_cents, total_cents
FROM purchase_request_items
WHERE pr_id = $1
`

func (q *Queries) ListPurchaseRequestItems(ctx context.Context, prID string) ([]PurchaseRequestItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequestItems, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequestItem
	for rows.Next() {
		var i PurchaseRequestItem
		if err := rows.Scan(
			&i.ID,
			&i.PrID,
			&i.Description,
			&i.Quantity,
			&i.UnitCostCents,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseRequests = `-- name: ListPurchaseRequests :many
SELECT pr.id, pr.pr_no, pr.jo_id, pr.status, pr.requested_by_role, pr.requested_at,
       pr.approved_by_role, pr.approved_at, pr.supplier, pr.notes,
       jo.jo_no AS job_order_no
FROM purchase_requests pr
LEFT JOIN job_orders jo ON jo.id = pr.jo_id
ORDER BY pr.requested_at DESC
`

type ListPurchaseRequestsRow struct {
	ID              string             `db:"id" json:"id"`
	PrNo            string             `db:"pr_no" json:"pr_no"`
	JoID            *string            `db:"jo_id" json:"jo_id"`
	Status          PrStatus           `db:"status" json:"status"`
	RequestedByRole string             `db:"requested_by_role" json:"requested_by_role"`
	RequestedAt     pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ApprovedByRole  *string            `db:"approved_by_role" json:"approved_by_role"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	Supplier        *string            `db:"supplier" json:"supplier"`
	Notes           *string            `db:"notes" json:"notes"`
	JobOrderNo      *string            `db:"job_order_no" json:"job_order_no"`
}

func (q *Queries) ListPurchaseRequests(ctx context.Context) ([]ListPurchaseRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseRequestsRow
	for rows.Next() {
		var i ListPurchaseRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrNo,
			&i.JoID,
			&i.Status,
			&i.RequestedByRole,
			&i.RequestedAt,
			&i.ApprovedByRole,
			&i.ApprovedAt,
			&i.Supplier,
			&i.Notes,
			&i.JobOrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotationItems = `-- name: ListQuotationItems :many
SELECT id, quote_id, item_type, description, quantity, unit_price_cents, discount_cents, net_amount_cents
FROM sales_quotation_items
WHERE quote_id = $1
`

func (q *Queries) ListQuotationItems(ctx context.Context, quoteID string) ([]SalesQuotationItem, error) {
	rows, err := q.db.Query(ctx, listQuotationItems, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesQuotationItem
	for rows.Next() {
		var i SalesQuotationItem
		if err := rows.Scan(
			&i.ID,
			&i.QuoteID,
			&i.ItemType,
			&i.Description,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.DiscountCents,
			&i.NetAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobOrders = `-- name: ListRecentJobOrders :many
SELECT jo.id, jo.jo_no, jo.sq_id, jo.customer_id, jo.vehicle_id, jo.advisor,
       jo.technician, jo.status,
       jo.total_estimated_labor_cents, jo.total_estimated_parts_cents,
       jo.actual_labor_cost_cents, jo.actual_parts_cost_cents, jo.billed_amount_cents, jo.net_profit_cents,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       jo.created_at, jo.updated_at
FROM job_orders jo
JOIN customers c ON c.id = jo.customer_id
JOIN vehicles v ON v.id = jo.vehicle_id
ORDER BY jo.created_at DESC
LIMIT $1
`

type ListRecentJobOrdersRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CustomerName             string             `db:"customer_name" json:"customer_name"`
	VehiclePlate             string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel         string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListRecentJobOrders(ctx context.Context, limit int32) ([]ListRecentJobOrdersRow, error) {
	rows, err := q.db.Query(ctx, listRecentJobOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentJobOrdersRow
	for rows.Next() {
		var i ListRecentJobOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.JoNo,
			&i.SqID,
			&i.CustomerID,
			&i.VehicleID,
			&i.Advisor,
			&i.Technician,
			&i.Status,
			&i.TotalEstimatedLaborCents,
			&i.TotalEstimatedPartsCents,
			&i.ActualLaborCostCents,
			&i.ActualPartsCostCents,
			&i.BilledAmountCents,
			&i.NetProfitCents,
			&i.CustomerName,
			&i.VehiclePlate,
			&i.VehicleMakeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesQuotations = `-- name: ListSalesQuotations :many
SELECT sq.id, sq.quote_no, sq.customer_id, sq.vehicle_id, sq.advisor,
       sq.total_labor_cents, sq.total_parts_cents, sq.net_total_cents, sq.status,
       c.name AS customer_name, v.plate_no AS vehicle_plate, v.make_model AS vehicle_make_model,
       sq.created_at, sq.updated_at
FROM sales_quotations sq
JOIN customers c ON c.id = sq.customer_id
JOIN vehicles v ON v.id = sq.vehicle_id
ORDER BY sq.created_at DESC
`

type ListSalesQuotationsRow struct {
	ID               string             `db:"id" json:"id"`
	QuoteNo          string             `db:"quote_no" json:"quote_no"`
	CustomerID       string             `db:"customer_id" json:"customer_id"`
	VehicleID        string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor          string             `db:"advisor" json:"advisor"`
	TotalLaborCents  int64              `db:"total_labor_cents" json:"total_labor_cents"`
	TotalPartsCents  int64              `db:"total_parts_cents" json:"total_parts_cents"`
	NetTotalCents    int64              `db:"net_total_cents" json:"net_total_cents"`
	Status           QuoteStatus        `db:"status" json:"status"`
	CustomerName     string             `db:"customer_name" json:"customer_name"`
	VehiclePlate     string             `db:"vehicle_plate" json:"vehicle_plate"`
	VehicleMakeModel string             `db:"vehicle_make_model" json:"vehicle_make_model"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSalesQuotations(ctx context.Context) ([]ListSalesQuotationsRow, error) {
	rows, err := q.db.Query(ctx, listSalesQuotations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesQuotationsRow
	for rows.Next() {
		var i ListSalesQuotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuoteNo,
			&i.CustomerID,
			&i.VehicleID,
			&i.Advisor,
			&i.TotalLaborCents,
			&i.TotalPartsCents,
			&i.NetTotalCents,
			&i.Status,
			&i.CustomerName,
			&i.VehiclePlate,
			&i.VehicleMakeModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceInvoices = `-- name: ListServiceInvoices :many
SELECT si.id, si.invoice_no, si.jo_id, si.customer_id, si.issue_date,
       si.subtotal_cents, si.vat_amount_cents, si.total_cents, si.amount_paid_cents,
       si.status, si.due_date, si.notes,
       c.name AS customer_name, jo.jo_no AS job_order_no
FROM service_invoices si
JOIN customers c ON c.id = si.customer_id
LEFT JOIN job_orders jo ON jo.id = si.jo_id
ORDER BY si.issue_date DESC
`

type ListServiceInvoicesRow struct {
	ID              string               `db:"id" json:"id"`
	InvoiceNo       string               `db:"invoice_no" json:"invoice_no"`
	JoID            *string              `db:"jo_id" json:"jo_id"`
	CustomerID      string               `db:"customer_id" json:"customer_id"`
	IssueDate       pgtype.Date          `db:"issue_date" json:"issue_date"`
	SubtotalCents   int64                `db:"subtotal_cents" json:"subtotal_cents"`
	VatAmountCents  int64                `db:"vat_amount_cents" json:"vat_amount_cents"`
	TotalCents      int64                `db:"total_cents" json:"total_cents"`
	AmountPaidCents int64                `db:"amount_paid_cents" json:"amount_paid_cents"`
	Status          ServiceInvoiceStatus `db:"status" json:"status"`
	DueDate         pgtype.Date          `db:"due_date" json:"due_date"`
	Notes           *string              `db:"notes" json:"notes"`
	CustomerName    string               `db:"customer_name" json:"customer_name"`
	JobOrderNo      *string              `db:"job_order_no" json:"job_order_no"`
}

func (q *Queries) ListServiceInvoices(ctx context.Context) ([]ListServiceInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listServiceInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceInvoicesRow
	for rows.Next() {
		var i ListServiceInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.JoID,
			&i.CustomerID,
			&i.IssueDate,
			&i.SubtotalCents,
			&i.VatAmountCents,
			&i.TotalCents,
			&i.AmountPaidCents,
			&i.Status,
			&i.DueDate,
			&i.Notes,
			&i.CustomerName,
			&i.JobOrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierInvoiceAllocations = `-- name: ListSupplierInvoiceAllocations :many
SELECT sa.id, sa.si_id, sa.jo_id, sa.amount_cents, sa.description, sa.created_at,
       jo.jo_no AS job_order_no
FROM supplier_invoice_allocations sa
JOIN job_orders jo ON jo.id = sa.jo_id
WHERE sa.si_id = $1
`

type ListSupplierInvoiceAllocationsRow struct {
	ID          string             `db:"id" json:"id"`
	SiID        string             `db:"si_id" json:"si_id"`
	JoID        string             `db:"jo_id" json:"jo_id"`
	AmountCents int64              `db:"amount_cents" json:"amount_cents"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	JobOrderNo  string             `db:"job_order_no" json:"job_order_no"`
}

func (q *Queries) ListSupplierInvoiceAllocations(ctx context.Context, siID string) ([]ListSupplierInvoiceAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listSupplierInvoiceAllocations, siID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierInvoiceAllocationsRow
	for rows.Next() {
		var i ListSupplierInvoiceAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiID,
			&i.JoID,
			&i.AmountCents,
			&i.Description,
			&i.CreatedAt,
			&i.JobOrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierInvoices = `-- name: ListSupplierInvoices :many
SELECT si.id, si.si_no, si.po_id, si.supplier, si.invoice_date, si.due_date,
       si.total_amount_cents, si.status, si.notes,
       po.po_no AS purchase_order_no
FROM supplier_invoices si
LEFT JOIN purchase_orders po ON po.id = si.po_id
ORDER BY si.si_no DESC
`

type ListSupplierInvoicesRow struct {
	ID               string      `db:"id" json:"id"`
	SiNo             string      `db:"si_no" json:"si_no"`
	PoID             *string     `db:"po_id" json:"po_id"`
	Supplier         *string     `db:"supplier" json:"supplier"`
	InvoiceDate      pgtype.Date `db:"invoice_date" json:"invoice_date"`
	DueDate          pgtype.Date `db:"due_date" json:"due_date"`
	TotalAmountCents int64       `db:"total_amount_cents" json:"total_amount_cents"`
	Status           SiStatus    `db:"status" json:"status"`
	Notes            *string     `db:"notes" json:"notes"`
	PurchaseOrderNo  *string     `db:"purchase_order_no" json:"purchase_order_no"`
}

func (q *Queries) ListSupplierInvoices(ctx context.Context) ([]ListSupplierInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listSupplierInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierInvoicesRow
	for rows.Next() {
		var i ListSupplierInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.SiNo,
			&i.PoID,
			&i.Supplier,
			&i.InvoiceDate,
			&i.DueDate,
			&i.TotalAmountCents,
			&i.Status,
			&i.Notes,
			&i.PurchaseOrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer, created_at, updated_at
FROM vehicles
ORDER BY created_at
`

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlateNo,
			&i.VinChassis,
			&i.EngineNo,
			&i.MakeModel,
			&i.Year,
			&i.Color,
			&i.Odometer,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByCustomer = `-- name: ListVehiclesByCustomer :many
SELECT id, customer_id, plate_no, vin_chassis, engine_no, make_model, year, color, odometer, created_at, updated_at
FROM vehicles
WHERE customer_id = $1
ORDER BY created_at
`

func (q *Queries) ListVehiclesByCustomer(ctx context.Context, customerID string) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlateNo,
			&i.VinChassis,
			&i.EngineNo,
			&i.MakeModel,
			&i.Year,
			&i.Color,
			&i.Odometer,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDisbursementPayment = `-- name: RecordDisbursementPayment :one
UPDATE disbursements
SET status = 'PAID', payment_method = $2, reference_no = $3, paid_at = $4, recorded_by_role = $5
WHERE id = $1
RETURNING id, disbursement_no, opex_request_id, supplier_invoice_id, amount_cents, status,
  payment_method, reference_no, paid_at, proof_attachment_key, recorded_by_role, created_at
`

type RecordDisbursementPaymentParams struct {
	ID             string             `db:"id" json:"id"`
	PaymentMethod  *string            `db:"payment_method" json:"payment_method"`
	ReferenceNo    *string            `db:"reference_no" json:"reference_no"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	RecordedByRole *string            `db:"recorded_by_role" json:"recorded_by_role"`
}

func (q *Queries) RecordDisbursementPayment(ctx context.Context, arg RecordDisbursementPaymentParams) (Disbursement, error) {
	row := q.db.QueryRow(ctx, recordDisbursementPayment,
		arg.ID,
		arg.PaymentMethod,
		arg.ReferenceNo,
		arg.PaidAt,
		arg.RecordedByRole,
	)
	var i Disbursement
	err := row.Scan(
		&i.ID,
		&i.DisbursementNo,
		&i.OpexRequestID,
		&i.SupplierInvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.PaymentMethod,
		&i.ReferenceNo,
		&i.PaidAt,
		&i.ProofAttachmentKey,
		&i.RecordedByRole,
		&i.CreatedAt,
	)
	return i, err
}

const sumActualCosts = `-- name: SumActualCosts :one
SELECT COALESCE(SUM(actual_labor_cost_cents + actual_parts_cost_cents), 0)::bigint FROM job_orders
`

func (q *Queries) SumActualCosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumActualCosts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumBilledAmount = `-- name: SumBilledAmount :one
SELECT COALESCE(SUM(billed_amount_cents), 0)::bigint FROM job_orders
`

func (q *Queries) SumBilledAmount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumBilledAmount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumSupplierInvoiceAllocationsByJO = `-- name: SumSupplierInvoiceAllocationsByJO :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint FROM supplier_invoice_allocations WHERE jo_id = $1
`

func (q *Queries) SumSupplierInvoiceAllocationsByJO(ctx context.Context, joID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumSupplierInvoiceAllocationsByJO, joID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, tin = $3, address = $4, phone = $5, email = $6, updated_at = now()
WHERE id = $1
RETURNING id, customer_no, name, tin, address, phone, email, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID      string  `db:"id" json:"id"`
	Name    string  `db:"name" json:"name"`
	Tin     *string `db:"tin" json:"tin"`
	Address *string `db:"address" json:"address"`
	Phone   *string `db:"phone" json:"phone"`
	Email   *string `db:"email" json:"email"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Tin,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerNo,
		&i.Name,
		&i.Tin,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDisbursementProof = `-- name: UpdateDisbursementProof :exec
UPDATE disbursements SET proof_attachment_key = $2 WHERE id = $1
`

type UpdateDisbursementProofParams struct {
	ID                 string  `db:"id" json:"id"`
	ProofAttachmentKey *string `db:"proof_attachment_key" json:"proof_attachment_key"`
}

func (q *Queries) UpdateDisbursementProof(ctx context.Context, arg UpdateDisbursementProofParams) error {
	_, err := q.db.Exec(ctx, updateDisbursementProof, arg.ID, arg.ProofAttachmentKey)
	return err
}

const updateJobOrderActualPartsCost = `-- name: UpdateJobOrderActualPartsCost :exec
UPDATE job_orders SET actual_parts_cost_cents = $2, updated_at = now() WHERE id = $1
`

type UpdateJobOrderActualPartsCostParams struct {
	ID                   string `db:"id" json:"id"`
	ActualPartsCostCents int64  `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
}

func (q *Queries) UpdateJobOrderActualPartsCost(ctx context.Context, arg UpdateJobOrderActualPartsCostParams) error {
	_, err := q.db.Exec(ctx, updateJobOrderActualPartsCost, arg.ID, arg.ActualPartsCostCents)
	return err
}

const updateJobOrderBilled = `-- name: UpdateJobOrderBilled :one
UPDATE job_orders
SET status = 'BILLED', billed_amount_cents = $2, net_profit_cents = $3, updated_at = now()
WHERE id = $1
RETURNING id, jo_no, sq_id, customer_id, vehicle_id, advisor, technician, status,
  total_estimated_labor_cents, total_estimated_parts_cents, actual_labor_cost_cents,
  actual_parts_cost_cents, billed_amount_cents, net_profit_cents, created_at, updated_at
`

type UpdateJobOrderBilledParams struct {
	ID                string `db:"id" json:"id"`
	BilledAmountCents int64  `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents    int64  `db:"net_profit_cents" json:"net_profit_cents"`
}

type UpdateJobOrderBilledRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateJobOrderBilled(ctx context.Context, arg UpdateJobOrderBilledParams) (UpdateJobOrderBilledRow, error) {
	row := q.db.QueryRow(ctx, updateJobOrderBilled, arg.ID, arg.BilledAmountCents, arg.NetProfitCents)
	var i UpdateJobOrderBilledRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobOrderNetProfit = `-- name: UpdateJobOrderNetProfit :exec
UPDATE job_orders
SET net_profit_cents = billed_amount_cents - actual_labor_cost_cents - actual_parts_cost_cents,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateJobOrderNetProfit(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateJobOrderNetProfit, id)
	return err
}

const updateJobOrderStatus = `-- name: UpdateJobOrderStatus :one
UPDATE job_orders
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, jo_no, sq_id, customer_id, vehicle_id, advisor, technician, status,
  total_estimated_labor_cents, total_estimated_parts_cents, actual_labor_cost_cents,
  actual_parts_cost_cents, billed_amount_cents, net_profit_cents, created_at, updated_at
`

type UpdateJobOrderStatusParams struct {
	ID     string   `db:"id" json:"id"`
	Status JoStatus `db:"status" json:"status"`
}

type UpdateJobOrderStatusRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateJobOrderStatus(ctx context.Context, arg UpdateJobOrderStatusParams) (UpdateJobOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, updateJobOrderStatus, arg.ID, arg.Status)
	var i UpdateJobOrderStatusRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobOrderTechnician = `-- name: UpdateJobOrderTechnician :one
UPDATE job_orders
SET technician = $2, updated_at = now()
WHERE id = $1
RETURNING id, jo_no, sq_id, customer_id, vehicle_id, advisor, technician, status,
  total_estimated_labor_cents, total_estimated_parts_cents, actual_labor_cost_cents,
  actual_parts_cost_cents, billed_amount_cents, net_profit_cents, created_at, updated_at
`

type UpdateJobOrderTechnicianParams struct {
	ID         string  `db:"id" json:"id"`
	Technician *string `db:"technician" json:"technician"`
}

type UpdateJobOrderTechnicianRow struct {
	ID                       string             `db:"id" json:"id"`
	JoNo                     string             `db:"jo_no" json:"jo_no"`
	SqID                     *string            `db:"sq_id" json:"sq_id"`
	CustomerID               string             `db:"customer_id" json:"customer_id"`
	VehicleID                string             `db:"vehicle_id" json:"vehicle_id"`
	Advisor                  string             `db:"advisor" json:"advisor"`
	Technician               *string            `db:"technician" json:"technician"`
	Status                   JoStatus           `db:"status" json:"status"`
	TotalEstimatedLaborCents int64              `db:"total_estimated_labor_cents" json:"total_estimated_labor_cents"`
	TotalEstimatedPartsCents int64              `db:"total_estimated_parts_cents" json:"total_estimated_parts_cents"`
	ActualLaborCostCents     int64              `db:"actual_labor_cost_cents" json:"actual_labor_cost_cents"`
	ActualPartsCostCents     int64              `db:"actual_parts_cost_cents" json:"actual_parts_cost_cents"`
	BilledAmountCents        int64              `db:"billed_amount_cents" json:"billed_amount_cents"`
	NetProfitCents           int64              `db:"net_profit_cents" json:"net_profit_cents"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateJobOrderTechnician(ctx context.Context, arg UpdateJobOrderTechnicianParams) (UpdateJobOrderTechnicianRow, error) {
	row := q.db.QueryRow(ctx, updateJobOrderTechnician, arg.ID, arg.Technician)
	var i UpdateJobOrderTechnicianRow
	err := row.Scan(
		&i.ID,
		&i.JoNo,
		&i.SqID,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.Technician,
		&i.Status,
		&i.TotalEstimatedLaborCents,
		&i.TotalEstimatedPartsCents,
		&i.ActualLaborCostCents,
		&i.ActualPartsCostCents,
		&i.BilledAmountCents,
		&i.NetProfitCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationStatus = `-- name: UpdateQuotationStatus :one
UPDATE sales_quotations
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, quote_no, customer_id, vehicle_id, advisor, total_labor_cents, total_parts_cents, net_total_cents, status, created_at, updated_at
`

type UpdateQuotationStatusParams struct {
	ID     string      `db:"id" json:"id"`
	Status QuoteStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) (SalesQuotation, error) {
	row := q.db.QueryRow(ctx, updateQuotationStatus, arg.ID, arg.Status)
	var i SalesQuotation
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.TotalLaborCents,
		&i.TotalPartsCents,
		&i.NetTotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationTotals = `-- name: UpdateQuotationTotals :one
UPDATE sales_quotations
SET total_labor_cents = $2, total_parts_cents = $3, net_total_cents = $4, updated_at = now()
WHERE id = $1
RETURNING id, quote_no, customer_id, vehicle_id, advisor, total_labor_cents, total_parts_cents, net_total_cents, status, created_at, updated_at
`

type UpdateQuotationTotalsParams struct {
	ID              string `db:"id" json:"id"`
	TotalLaborCents int64  `db:"total_labor_cents" json:"total_labor_cents"`
	TotalPartsCents int64  `db:"total_parts_cents" json:"total_parts_cents"`
	NetTotalCents   int64  `db:"net_total_cents" json:"net_total_cents"`
}

func (q *Queries) UpdateQuotationTotals(ctx context.Context, arg UpdateQuotationTotalsParams) (SalesQuotation, error) {
	row := q.db.QueryRow(ctx, updateQuotationTotals,
		arg.ID,
		arg.TotalLaborCents,
		arg.TotalPartsCents,
		arg.NetTotalCents,
	)
	var i SalesQuotation
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.VehicleID,
		&i.Advisor,
		&i.TotalLaborCents,
		&i.TotalPartsCents,
		&i.NetTotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceInvoicePaymentStatus = `-- name: UpdateServiceInvoicePaymentStatus :one
UPDATE service_invoices
SET amount_paid_cents = $2, status = $3
WHERE id = $1
RETURNING id, invoice_no, jo_id, customer_id, issue_date, subtotal_cents, vat_amount_cents,
  total_cents, amount_paid_cents, status, due_date, notes
`

type UpdateServiceInvoicePaymentStatusParams struct {
	ID              string               `db:"id" json:"id"`
	AmountPaidCents int64                `db:"amount_paid_cents" json:"amount_paid_cents"`
	Status          ServiceInvoiceStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateServiceInvoicePaymentStatus(ctx context.Context, arg UpdateServiceInvoicePaymentStatusParams) (ServiceInvoice, error) {
	row := q.db.QueryRow(ctx, updateServiceInvoicePaymentStatus, arg.ID, arg.AmountPaidCents, arg.Status)
	var i ServiceInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.JoID,
		&i.CustomerID,
		&i.IssueDate,
		&i.SubtotalCents,
		&i.VatAmountCents,
		&i.TotalCents,
		&i.AmountPaidCents,
		&i.Status,
		&i.DueDate,
		&i.Notes,
	)
	return i, err
}

const updateSupplierInvoiceStatus = `-- name: UpdateSupplierInvoiceStatus :one
UPDATE supplier_invoices
SET status = $2
WHERE id = $1
RETURNING id, si_no, po_id, supplier, invoice_date, due_date, total_amount_cents, status, notes
`

type UpdateSupplierInvoiceStatusParams struct {
	ID     string   `db:"id" json:"id"`
	Status SiStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateSupplierInvoiceStatus(ctx context.Context, arg UpdateSupplierInvoiceStatusParams) (SupplierInvoice, error) {
	row := q.db.QueryRow(ctx, updateSupplierInvoiceStatus, arg.ID, arg.Status)
	var i SupplierInvoice
	err := row.Scan(
		&i.ID,
		&i.SiNo,
		&i.PoID,
		&i.Supplier,
		&i.InvoiceDate,
		&i.DueDate,
		&i.TotalAmountCents,
		&i.Status,
		&i.Notes,
	)
	return i, err
}
